format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[directory]
style = "#c8a96e bold"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "#8a8070"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "#8a4f3e"

[character]
success_symbol = "[❯](#c8a96e)"
error_symbol = "[❯](#8a4f3e)"

[line_break]
disabled = false
